events {}

http {
    # Nouveau format de log pour identifier le Virtual Host
    log_format log_per_virtualhost '[$host] $remote_addr [$time_local] $status "$request" $body_bytes_sent';
    access_log /dev/stdout log_per_virtualhost;

    # Site WWW
    server {
        listen 80;
        server_name www.m1-4.ephec-ti.be;
        index index.php index.html;
        root /var/www/html/www/;

        # --- AJOUT DU BLOC PHP CI-DESSOUS ---
        location ~* \.php$ {
            # Remplace bien par l'IP de ton container PHP (docker inspect)
            fastcgi_pass php:9000; 
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
        # ------------------------------------
    }

    # Site BLOG
    server {
        listen 80;
        server_name blog.m1-4.ephec-ti.be;
        index index.html;
        root /var/www/html/blog/;
    }
}
