events {}

http {
    server_tokens off; # Hardening : Cache la version de Nginx

    log_format log_per_virtualhost '[$host] $remote_addr [$time_local] $status "$request" $body_bytes_sent';
    access_log /dev/stdout log_per_virtualhost;

    # Sécurité : Limites DOS
    client_body_buffer_size 10K;
    client_header_buffer_size 1k;
    client_max_body_size 8m;
    large_client_header_buffers 2 1k;

    # --- REDIRECTION HTTP vers HTTPS ---
    server {
        listen 80;
        server_name www.m1-4.ephec-ti.be blog.m1-4.ephec-ti.be;
        return 301 https://$host$request_uri;
    }

    # --- CONFIGURATION HTTPS (Site WWW) ---
    server {
        listen 443 ssl;
        server_name www.m1-4.ephec-ti.be;

        # Chemins vers tes certificats (montés via le volume dans docker-compose)
        ssl_certificate /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

        # Protocoles sécurisés uniquement
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        index index.php index.html;
        root /var/www/html/www/;

        # Headers de sécurité
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        location ~* \.php$ {
            fastcgi_pass php:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_hide_header X-Powered-By;
        }
    }

    # --- CONFIGURATION HTTPS (Site BLOG) ---
    server {
        listen 443 ssl;
        server_name blog.m1-4.ephec-ti.be;

        ssl_certificate /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

        index index.html;
        root /var/www/html/blog/;

        add_header X-Frame-Options "SAMEORIGIN";
    }
}
