events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    # Redirection automatique vers HTTPS
    server {
        listen 80;
        server_name m1-4.ephec-ti.be www.m1-4.ephec-ti.be blog.m1-4.ephec-ti.be;
        return 301 https://$host$request_uri;
    }

    # Configuration pour www et m1-4
    server {
        listen 443 ssl;
        server_name www.m1-4.ephec-ti.be m1-4.ephec-ti.be;

        # Header pour forcer le HTTPS sur les ressources internes (images, scripts)
        add_header Content-Security-Policy "upgrade-insecure-requests";

        ssl_certificate     /etc/letsencrypt/live/m1-4.ephec-ti.be/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/m1-4.ephec-ti.be/privkey.pem;

        root /var/www/html/www;
        index index.php index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            fastcgi_pass php:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    # Configuration pour le Blog
    server {
        listen 443 ssl;
        server_name blog.m1-4.ephec-ti.be;

        add_header Content-Security-Policy "upgrade-insecure-requests";

        ssl_certificate     /etc/letsencrypt/live/m1-4.ephec-ti.be/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/m1-4.ephec-ti.be/privkey.pem;

        root /var/www/html/blog;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
