# logstash/pipeline/logstash.conf

input {
  tcp {
    port => 5000
    codec => json_lines # On s'attend à recevoir des lignes JSON de Flask
  }
}

# La section filter est optionnelle ici, mais c'est là qu'on pourrait
# parser des dates, ajouter/supprimer des champs, utiliser grok pour du texte non structuré, etc.
# Si on voulait s'assurer que event_timestamp devienne le @timestamp principal:
# filter {
#   if [extra][event_timestamp] {
#     date {
#       match => [ "[extra][event_timestamp]", "ISO8601" ]
#       target => "@timestamp"
#     }
#   }
# }

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"] # Adresse du service Elasticsearch
    index => "flask-logs-%{+YYYY.MM.dd}"  # Nom de l'index dans Elasticsearch (quotidien)
  }
  # Pour le débogage, on peut aussi afficher les logs dans la console de Logstash
  # stdout { codec => rubydebug }
}
