options {
  directory "/var/cache/bind";
  version "not currently available";
  allow-query { any; };
  allow-query-cache { none; };
  recursion no;
  listen-on { any; };
  listen-on-v6 { any; };
};

# Supprime ou commente tout ce bloc qui crée le conflit
# zone "m1-4.ephec-ti.be." {
#   type master;
#   allow-transfer { none; };
#   inline-signing yes;
#   dnssec-policy default;
# };

include "/etc/bind/named.conf.local";
