options {
  directory "/var/cache/bind";
  version "not currently available";
  allow-query { any; };      # Autorise les requêtes de partout
  allow-query-cache { none; };
  recursion no;              # INTERDIT la récursion
};

zone "l1-1.ephec-ti.be." {
  type master;
  file "/var/lib/bind/db.woodytoys.zone";
  allow-transfer { none; };
  inline-signing yes;        # Active la signature DNSSEC
  dnssec-policy default;     # Utilise la politique par défaut
};
